[cosmic-ray]
module-path = "D:/Projects/sample repo/Cyclomatic Complexity/github-actions-cicd-example/actionscicd/somecode.py"
timeout = 20.0
excluded-modules = []
test-command = '"D:\\Projects\\sample repo\\Mutation Score\\tools\\mutmut\\.venv\\Scripts\\python.exe" -m pytest -q'

[cosmic-ray.distributor]
name = "local"
